export const BLOCKED_COMMANDS = [
  'sudo *',
  'rm -rf /',
  'rm -rf ~',
  'rm -rf /*',
  'mkfs *',
  'dd if=*',
  'chmod 777 /',
  'chown * /',
  ':(){ :|:& };:',
  'shutdown *',
  'reboot *',
  'halt *',
  'init 0',
  'init 6',
  'kill -9 1',
  '> /dev/sda',
  'mv /* /dev/null',
];

export const AUTO_APPROVED_COMMANDS = [
  'ls *',
  'cat *',
  'pwd',
  'which *',
  'node *',
  'npm run *',
  'npm test *',
  'npm list *',
  'git status *',
  'git diff *',
  'git log *',
  'git branch *',
  'echo *',
  'head *',
  'tail *',
  'wc *',
  'find *',
  'grep *',
  'rg *',
  'ps *',
  'df *',
  'du *',
  'uname *',
];

export const NEEDS_APPROVAL_COMMANDS = [
  'npm publish *',
  'git push *',
  'docker *',
  'curl * | sh',
  'curl * | bash',
  'wget * | sh',
  'pip install *',
  'pip3 install *',
  'rm -r *',
  'rm -rf *',
  'mv *',
  'cp -r *',
  'chmod *',
  'mkdir *',
  'rmdir *',
];